import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    padding: 22,
    paddingBottom: 34,
  },
  header: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#A2B1C7',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  headerTitle: {
    color: '#1C2A40',
    fontSize: 18,
    fontWeight: '800',
  },
  headerSpacer: {
    width: 42,
  },
  heroCard: {
    minHeight: 270,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 25,
    shadowColor: '#A2B1C7',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  largeIconCircle: {
    width: 124,
    height: 124,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 19,
  },
  deviceName: {
    color: '#23324B',
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  deviceRoom: {
    color: '#74839A',
    fontSize: 13,
    marginTop: 6,
    textAlign: 'center',
  },
  statusPill: {
    minWidth: 65,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 6,
    alignItems: 'center',
    marginTop: 14,
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    color: '#1C2A40',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 28,
    marginBottom: 9,
  },
  description: {
    color: '#74839A',
    fontSize: 14,
    lineHeight: 21,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 22,
  },
  infoCard: {
    flex: 1,
    minHeight: 108,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 15,
    shadowColor: '#A2B1C7',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  infoLabel: {
    color: '#7C899E',
    fontSize: 11,
    marginTop: 12,
  },
  infoValue: {
    color: '#23324B',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 3,
  },
  actionButton: {
    height: 54,
    borderRadius: 17,
    backgroundColor: '#2E6BCE',
    marginTop: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  actionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
