import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    padding: 22,
    paddingBottom: 34,
  },
  topBar: {
    minHeight: 86,
    marginHorizontal: -22,
    marginTop: -22,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 17,
    backgroundColor: '#203A65',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.13)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyebrow: {
    color: '#BBD4FF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.3,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 1,
  },
  topBarIcon: {
    marginLeft: 'auto',
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.13)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryRow: {
    marginTop: 27,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryTitle: {
    color: '#1C2A40',
    fontSize: 21,
    fontWeight: '800',
  },
  summaryText: {
    color: '#75839A',
    fontSize: 13,
    marginTop: 4,
  },
  summaryBadge: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: '#E4EEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryBadgeText: {
    color: '#2E6BCE',
    fontSize: 18,
    fontWeight: '800',
  },
  list: {
    gap: 13,
  },
  deviceRow: {
    minHeight: 112,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#A2B1C7',
    shadowOpacity: 0.13,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceCopy: {
    flex: 1,
    marginLeft: 15,
  },
  deviceName: {
    color: '#23324B',
    fontSize: 16,
    fontWeight: '800',
  },
  deviceMeta: {
    color: '#7C899E',
    fontSize: 12,
    marginTop: 4,
  },
  statusLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 9,
    gap: 6,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  statusText: {
    color: '#62728A',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.985 }],
  },
});
