import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F8FC',
  },
  container: {
    padding: 22,
    paddingBottom: 34,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 28,
  },
  logoCircle: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#E4EEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyebrow: {
    color: '#2E6BCE',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  title: {
    color: '#1C2A40',
    fontSize: 25,
    fontWeight: '800',
    marginTop: 1,
  },
  headerBadge: {
    marginLeft: 'auto',
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: '#E4F6EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeBlock: {
    marginBottom: 25,
  },
  welcomeTitle: {
    color: '#1C2A40',
    fontSize: 23,
    fontWeight: '700',
    marginBottom: 6,
  },
  welcomeText: {
    color: '#75839A',
    fontSize: 15,
  },
  sectionHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 13,
  },
  sectionTitle: {
    color: '#1C2A40',
    fontSize: 18,
    fontWeight: '800',
  },
  deviceCount: {
    color: '#71829D',
    fontSize: 13,
    fontWeight: '600',
  },
  deviceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 13,
  },
  deviceCard: {
    width: '48.2%',
    minHeight: 176,
    borderRadius: 19,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#A2B1C7',
    shadowOpacity: 0.14,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  iconCircle: {
    width: 62,
    height: 62,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 11,
  },
  deviceName: {
    color: '#23324B',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  deviceRoom: {
    color: '#74839A',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
  },
  statusPill: {
    minWidth: 57,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 5,
    alignItems: 'center',
    marginTop: 11,
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  viewButton: {
    height: 56,
    borderRadius: 17,
    backgroundColor: '#2E6BCE',
    marginTop: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 11,
    shadowColor: '#2E6BCE',
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  viewButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
